heal_config:
  name: pot_low_health_high_health_ssa
  health_bar:
    # y position of the healh bar search pos
    y: 34
    # x position to use health pot when it is not green
    pot_x: 255
    # x position to use healing spell when it is not green
    spell_x: 860
  mana_bar:
    # y position of the mana bar search pos
    y: 31
    # y position to use mana pot when bar is not blue-ish
    pot_x: 1300
    # y position to use mana pot when bar is not blue-ish and there is no creature on the battle
    high_mana_pot_x: 950
  heal_service:
    spell_heal_key: f1
    pot_heal_key: f2
    heal_cd: 1
  mana_service:
    pot_mana_key: f3
    pot_until_high_mana: True
    pot_cd: 1.3
